framework:
    messenger:
        transports:
            amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            '*': amqp

        buses:
            default:
                middleware:
                    - 'messenger.middleware.validation'
